name: small_scale_university
description: A Flutter project for The Grassroots Football Clubs around the world.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  adaptive_theme: ^3.6.0
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  awesome_snackbar_content: ^0.1.4
  auto_size_text: ^3.0.0
  avatar_glow: ^3.0.1
  blurrycontainer: ^2.1.0
  cached_network_image: ^3.4.1
  clay_containers: ^0.3.4
  cloud_firestore: ^5.5.1
  cloud_functions: ^5.2.0
  collection: ^1.18.0
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  dart_openai: ^5.1.0
  draggable_scrollbar: ^0.1.0
  esys_flutter_share_plus: ^2.3.0
  file_picker: ^8.1.4
  firebase_analytics: ^11.3.6
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.2.0
  firebase_database: ^11.2.0
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.7
  fl_chart: ^0.69.2
  flutter_animate: ^4.5.2
  flutter_bloc: ^7.0.0   # Adjust if you find that a higher version is needed
  flutter_blur: ^0.0.2
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^5.2.1
  flutter_email_sender: ^6.0.3
  flutter_gemini: ^3.0.0
  flutter_inappwebview: ^6.1.5
  flutter_inset_box_shadow: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_local_notifications: ^18.0.1
  flutter_neumorphic: ^3.2.0
  #  flutter_pdf: ^0.0.1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_spinner_time_picker: ^0.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_stripe: ^11.3.0
  flutter_swiper_null_safety: ^1.0.2
  flutter_text_drawable: ^1.0.0
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.8.0
  #  giffy_dialog: ^2.1.0
  glassmorphism: ^3.0.0
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  google_nav_bar: ^5.0.7
  grouped_list: ^6.0.0
  http: ^1.2.2
  image: ^4.3.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  intl: ^0.19.0   # Update to match flutter_localizations
  langchain: ^0.7.7+1
  launch_review: ^3.0.1
  line_icons: ^2.0.3
  lottie: ^3.2.0
  mailer: ^6.3.0
  material_design_icons_flutter: ^7.0.7296
  onesignal_flutter: ^5.2.7
  open_file: ^3.5.10
  otp_text_field: ^1.1.3
  parallax_rain: ^1.1.1
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pie_chart: ^5.4.0
  printing: ^5.13.4
  provider: ^6.1.2
  rename_app: ^1.6.1
  rxdart: ^0.28.0
  screenshot: ^3.0.0
  share_plus: ^10.1.3
  shared_preferences: ^2.3.4
  showcaseview: ^3.0.0
  shimmer: ^3.0.0
  simple_icons: ^10.1.3
  sms_autofill: ^2.4.1
  sticky_grouped_list: ^3.1.0
  syncfusion_flutter_charts: ^27.2.5
  syncfusion_flutter_core: ^27.2.5
  syncfusion_flutter_datagrid: ^27.2.5
  syncfusion_flutter_gauges: ^27.2.5
  telephony: ^0.2.0
  timelines: ^0.1.0
  timeline_tile: ^2.0.0
  toast: ^0.3.0
  toastification: ^2.3.0
  transparent_image: ^2.0.1
  twilio_flutter: ^0.9.0
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  vs_scrollbar: ^1.0.0
  youtube: ^2.0.0
  youtube_player_flutter: ^9.1.1

dependency_overrides:
  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true-7
  image_path: "assets/images/ng_uni_icon.jpeg"
  remove_alpha_ios: true
#  image_path_android: "assets/images/the_gfa_logo_android.png"
#  image_path_ios: "assets/images/the_gfa_logo_ios.png"

flutter:
  assets:
    - assets/images/
#    - assets/videos/
#    - assets/json/
    - assets/
    - .env
  uses-material-design: true
